/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMeetingRoomsRouteImport } from './routes/_app.meeting-rooms'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave-requests'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppTicketsIndexRouteImport } from './routes/_app.tickets.index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/_app.tickets.$ticketId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingRoomsRoute = AppMeetingRoomsRouteImport.update({
  id: '/meeting-rooms',
  path: '/meeting-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assets': typeof AppAssetsRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/meeting-rooms': typeof AppMeetingRoomsRoute
  '/profile': typeof AppProfileRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assets': typeof AppAssetsRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/meeting-rooms': typeof AppMeetingRoomsRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/tickets': typeof AppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/leave-requests': typeof AppLeaveRequestsRoute
  '/_app/meeting-rooms': typeof AppMeetingRoomsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/assets'
    | '/leave-requests'
    | '/meeting-rooms'
    | '/profile'
    | '/tickets'
    | '/tickets/$ticketId'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/announcements'
    | '/assets'
    | '/leave-requests'
    | '/meeting-rooms'
    | '/profile'
    | '/'
    | '/tickets/$ticketId'
    | '/tickets'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/announcements'
    | '/_app/assets'
    | '/_app/leave-requests'
    | '/_app/meeting-rooms'
    | '/_app/profile'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/tickets/$ticketId'
    | '/_app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting-rooms': {
      id: '/_app/meeting-rooms'
      path: '/meeting-rooms'
      fullPath: '/meeting-rooms'
      preLoaderRoute: typeof AppMeetingRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests': {
      id: '/_app/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
  }
}

interface AppTicketsRouteChildren {
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRoute
  AppMeetingRoomsRoute: typeof AppMeetingRoomsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRoute,
  AppMeetingRoomsRoute: AppMeetingRoomsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
