/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppAssignedTicketsRouteImport } from './routes/_app.assigned-tickets'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave-requests'
import { Route as AppMeetingRoomsRouteImport } from './routes/_app.meeting-rooms'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppAssetsIndexRouteImport } from './routes/_app.assets.index'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app.assets.$assetId'
import { Route as AppAssetsAllRouteImport } from './routes/_app.assets.all'
import { Route as AppLeaveRequestsIndexRouteImport } from './routes/_app.leave-requests.index'
import { Route as AppLeaveRequestsLeaveIdRouteImport } from './routes/_app.leave-requests.$leaveId'
import { Route as AppLeaveRequestsAllRouteImport } from './routes/_app.leave-requests.all'
import { Route as AppMeetingRoomsIndexRouteImport } from './routes/_app.meeting-rooms.index'
import { Route as AppTicketsIndexRouteImport } from './routes/_app.tickets.index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/_app.tickets.$ticketId'
import { Route as AppMeetingRoomsBookingsIndexRouteImport } from './routes/_app.meeting-rooms.bookings.index'
import { Route as AppMeetingRoomsBookingsBookingIdRouteImport } from './routes/_app.meeting-rooms.bookings.$bookingId'
import { Route as AppMeetingRoomsRoomsIndexRouteImport } from './routes/_app.meeting-rooms.rooms.index'
import { Route as AppMeetingRoomsRoomsRoomIdRouteImport } from './routes/_app.meeting-rooms.rooms.$roomId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignedTicketsRoute = AppAssignedTicketsRouteImport.update({
  id: '/assigned-tickets',
  path: '/assigned-tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingRoomsRoute = AppMeetingRoomsRouteImport.update({
  id: '/meeting-rooms',
  path: '/meeting-rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsAllRoute = AppAssetsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppLeaveRequestsIndexRoute = AppLeaveRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeaveRequestsRoute,
} as any)
const AppLeaveRequestsLeaveIdRoute = AppLeaveRequestsLeaveIdRouteImport.update({
  id: '/$leaveId',
  path: '/$leaveId',
  getParentRoute: () => AppLeaveRequestsRoute,
} as any)
const AppLeaveRequestsAllRoute = AppLeaveRequestsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppLeaveRequestsRoute,
} as any)
const AppMeetingRoomsIndexRoute = AppMeetingRoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMeetingRoomsRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppTicketsRoute,
} as any)
const AppMeetingRoomsBookingsIndexRoute =
  AppMeetingRoomsBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AppMeetingRoomsRoute,
  } as any)
const AppMeetingRoomsBookingsBookingIdRoute =
  AppMeetingRoomsBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AppMeetingRoomsRoute,
  } as any)
const AppMeetingRoomsRoomsIndexRoute =
  AppMeetingRoomsRoomsIndexRouteImport.update({
    id: '/rooms/',
    path: '/rooms/',
    getParentRoute: () => AppMeetingRoomsRoute,
  } as any)
const AppMeetingRoomsRoomsRoomIdRoute =
  AppMeetingRoomsRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AppMeetingRoomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assets': typeof AppAssetsRouteWithChildren
  '/assigned-tickets': typeof AppAssignedTicketsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/leave-requests': typeof AppLeaveRequestsRouteWithChildren
  '/meeting-rooms': typeof AppMeetingRoomsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/tickets': typeof AppTicketsRouteWithChildren
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/assets/all': typeof AppAssetsAllRoute
  '/leave-requests/$leaveId': typeof AppLeaveRequestsLeaveIdRoute
  '/leave-requests/all': typeof AppLeaveRequestsAllRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/leave-requests/': typeof AppLeaveRequestsIndexRoute
  '/meeting-rooms/': typeof AppMeetingRoomsIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/meeting-rooms/bookings/$bookingId': typeof AppMeetingRoomsBookingsBookingIdRoute
  '/meeting-rooms/rooms/$roomId': typeof AppMeetingRoomsRoomsRoomIdRoute
  '/meeting-rooms/bookings/': typeof AppMeetingRoomsBookingsIndexRoute
  '/meeting-rooms/rooms/': typeof AppMeetingRoomsRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/assigned-tickets': typeof AppAssignedTicketsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/': typeof AppIndexRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/assets/all': typeof AppAssetsAllRoute
  '/leave-requests/$leaveId': typeof AppLeaveRequestsLeaveIdRoute
  '/leave-requests/all': typeof AppLeaveRequestsAllRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/assets': typeof AppAssetsIndexRoute
  '/leave-requests': typeof AppLeaveRequestsIndexRoute
  '/meeting-rooms': typeof AppMeetingRoomsIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/meeting-rooms/bookings/$bookingId': typeof AppMeetingRoomsBookingsBookingIdRoute
  '/meeting-rooms/rooms/$roomId': typeof AppMeetingRoomsRoomsRoomIdRoute
  '/meeting-rooms/bookings': typeof AppMeetingRoomsBookingsIndexRoute
  '/meeting-rooms/rooms': typeof AppMeetingRoomsRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/assigned-tickets': typeof AppAssignedTicketsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/leave-requests': typeof AppLeaveRequestsRouteWithChildren
  '/_app/meeting-rooms': typeof AppMeetingRoomsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tickets': typeof AppTicketsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/_app/assets/all': typeof AppAssetsAllRoute
  '/_app/leave-requests/$leaveId': typeof AppLeaveRequestsLeaveIdRoute
  '/_app/leave-requests/all': typeof AppLeaveRequestsAllRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/leave-requests/': typeof AppLeaveRequestsIndexRoute
  '/_app/meeting-rooms/': typeof AppMeetingRoomsIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/meeting-rooms/bookings/$bookingId': typeof AppMeetingRoomsBookingsBookingIdRoute
  '/_app/meeting-rooms/rooms/$roomId': typeof AppMeetingRoomsRoomsRoomIdRoute
  '/_app/meeting-rooms/bookings/': typeof AppMeetingRoomsBookingsIndexRoute
  '/_app/meeting-rooms/rooms/': typeof AppMeetingRoomsRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/assets'
    | '/assigned-tickets'
    | '/audit-logs'
    | '/leave-requests'
    | '/meeting-rooms'
    | '/notifications'
    | '/profile'
    | '/tickets'
    | '/assets/$assetId'
    | '/assets/all'
    | '/leave-requests/$leaveId'
    | '/leave-requests/all'
    | '/tickets/$ticketId'
    | '/assets/'
    | '/leave-requests/'
    | '/meeting-rooms/'
    | '/tickets/'
    | '/meeting-rooms/bookings/$bookingId'
    | '/meeting-rooms/rooms/$roomId'
    | '/meeting-rooms/bookings/'
    | '/meeting-rooms/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/announcements'
    | '/assigned-tickets'
    | '/audit-logs'
    | '/notifications'
    | '/profile'
    | '/'
    | '/assets/$assetId'
    | '/assets/all'
    | '/leave-requests/$leaveId'
    | '/leave-requests/all'
    | '/tickets/$ticketId'
    | '/assets'
    | '/leave-requests'
    | '/meeting-rooms'
    | '/tickets'
    | '/meeting-rooms/bookings/$bookingId'
    | '/meeting-rooms/rooms/$roomId'
    | '/meeting-rooms/bookings'
    | '/meeting-rooms/rooms'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/announcements'
    | '/_app/assets'
    | '/_app/assigned-tickets'
    | '/_app/audit-logs'
    | '/_app/leave-requests'
    | '/_app/meeting-rooms'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/assets/$assetId'
    | '/_app/assets/all'
    | '/_app/leave-requests/$leaveId'
    | '/_app/leave-requests/all'
    | '/_app/tickets/$ticketId'
    | '/_app/assets/'
    | '/_app/leave-requests/'
    | '/_app/meeting-rooms/'
    | '/_app/tickets/'
    | '/_app/meeting-rooms/bookings/$bookingId'
    | '/_app/meeting-rooms/rooms/$roomId'
    | '/_app/meeting-rooms/bookings/'
    | '/_app/meeting-rooms/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assigned-tickets': {
      id: '/_app/assigned-tickets'
      path: '/assigned-tickets'
      fullPath: '/assigned-tickets'
      preLoaderRoute: typeof AppAssignedTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests': {
      id: '/_app/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meeting-rooms': {
      id: '/_app/meeting-rooms'
      path: '/meeting-rooms'
      fullPath: '/meeting-rooms'
      preLoaderRoute: typeof AppMeetingRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/assets/all': {
      id: '/_app/assets/all'
      path: '/all'
      fullPath: '/assets/all'
      preLoaderRoute: typeof AppAssetsAllRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/leave-requests/': {
      id: '/_app/leave-requests/'
      path: '/'
      fullPath: '/leave-requests/'
      preLoaderRoute: typeof AppLeaveRequestsIndexRouteImport
      parentRoute: typeof AppLeaveRequestsRoute
    }
    '/_app/leave-requests/$leaveId': {
      id: '/_app/leave-requests/$leaveId'
      path: '/$leaveId'
      fullPath: '/leave-requests/$leaveId'
      preLoaderRoute: typeof AppLeaveRequestsLeaveIdRouteImport
      parentRoute: typeof AppLeaveRequestsRoute
    }
    '/_app/leave-requests/all': {
      id: '/_app/leave-requests/all'
      path: '/all'
      fullPath: '/leave-requests/all'
      preLoaderRoute: typeof AppLeaveRequestsAllRouteImport
      parentRoute: typeof AppLeaveRequestsRoute
    }
    '/_app/meeting-rooms/': {
      id: '/_app/meeting-rooms/'
      path: '/'
      fullPath: '/meeting-rooms/'
      preLoaderRoute: typeof AppMeetingRoomsIndexRouteImport
      parentRoute: typeof AppMeetingRoomsRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppTicketsRoute
    }
    '/_app/meeting-rooms/bookings/': {
      id: '/_app/meeting-rooms/bookings/'
      path: '/bookings'
      fullPath: '/meeting-rooms/bookings/'
      preLoaderRoute: typeof AppMeetingRoomsBookingsIndexRouteImport
      parentRoute: typeof AppMeetingRoomsRoute
    }
    '/_app/meeting-rooms/bookings/$bookingId': {
      id: '/_app/meeting-rooms/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/meeting-rooms/bookings/$bookingId'
      preLoaderRoute: typeof AppMeetingRoomsBookingsBookingIdRouteImport
      parentRoute: typeof AppMeetingRoomsRoute
    }
    '/_app/meeting-rooms/rooms/': {
      id: '/_app/meeting-rooms/rooms/'
      path: '/rooms'
      fullPath: '/meeting-rooms/rooms/'
      preLoaderRoute: typeof AppMeetingRoomsRoomsIndexRouteImport
      parentRoute: typeof AppMeetingRoomsRoute
    }
    '/_app/meeting-rooms/rooms/$roomId': {
      id: '/_app/meeting-rooms/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/meeting-rooms/rooms/$roomId'
      preLoaderRoute: typeof AppMeetingRoomsRoomsRoomIdRouteImport
      parentRoute: typeof AppMeetingRoomsRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppAssetsAllRoute: typeof AppAssetsAllRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppAssetsAllRoute: AppAssetsAllRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppLeaveRequestsRouteChildren {
  AppLeaveRequestsLeaveIdRoute: typeof AppLeaveRequestsLeaveIdRoute
  AppLeaveRequestsAllRoute: typeof AppLeaveRequestsAllRoute
  AppLeaveRequestsIndexRoute: typeof AppLeaveRequestsIndexRoute
}

const AppLeaveRequestsRouteChildren: AppLeaveRequestsRouteChildren = {
  AppLeaveRequestsLeaveIdRoute: AppLeaveRequestsLeaveIdRoute,
  AppLeaveRequestsAllRoute: AppLeaveRequestsAllRoute,
  AppLeaveRequestsIndexRoute: AppLeaveRequestsIndexRoute,
}

const AppLeaveRequestsRouteWithChildren =
  AppLeaveRequestsRoute._addFileChildren(AppLeaveRequestsRouteChildren)

interface AppMeetingRoomsRouteChildren {
  AppMeetingRoomsIndexRoute: typeof AppMeetingRoomsIndexRoute
  AppMeetingRoomsBookingsBookingIdRoute: typeof AppMeetingRoomsBookingsBookingIdRoute
  AppMeetingRoomsRoomsRoomIdRoute: typeof AppMeetingRoomsRoomsRoomIdRoute
  AppMeetingRoomsBookingsIndexRoute: typeof AppMeetingRoomsBookingsIndexRoute
  AppMeetingRoomsRoomsIndexRoute: typeof AppMeetingRoomsRoomsIndexRoute
}

const AppMeetingRoomsRouteChildren: AppMeetingRoomsRouteChildren = {
  AppMeetingRoomsIndexRoute: AppMeetingRoomsIndexRoute,
  AppMeetingRoomsBookingsBookingIdRoute: AppMeetingRoomsBookingsBookingIdRoute,
  AppMeetingRoomsRoomsRoomIdRoute: AppMeetingRoomsRoomsRoomIdRoute,
  AppMeetingRoomsBookingsIndexRoute: AppMeetingRoomsBookingsIndexRoute,
  AppMeetingRoomsRoomsIndexRoute: AppMeetingRoomsRoomsIndexRoute,
}

const AppMeetingRoomsRouteWithChildren = AppMeetingRoomsRoute._addFileChildren(
  AppMeetingRoomsRouteChildren,
)

interface AppTicketsRouteChildren {
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppTicketsRouteChildren: AppTicketsRouteChildren = {
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppTicketsRouteWithChildren = AppTicketsRoute._addFileChildren(
  AppTicketsRouteChildren,
)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppAssignedTicketsRoute: typeof AppAssignedTicketsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRouteWithChildren
  AppMeetingRoomsRoute: typeof AppMeetingRoomsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTicketsRoute: typeof AppTicketsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppAssignedTicketsRoute: AppAssignedTicketsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRouteWithChildren,
  AppMeetingRoomsRoute: AppMeetingRoomsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTicketsRoute: AppTicketsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
